-- ====================================================
-- BILLBOARD SETUP FOR SUPABASE
-- ====================================================
-- Run these commands in your Supabase SQL Editor

-- 1. Create billboards table
CREATE TABLE IF NOT EXISTS billboards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    "buttonText" VARCHAR(100) NOT NULL,
    "buttonUrl" VARCHAR(500) NOT NULL,
    "backgroundImage" VARCHAR(500) NOT NULL,
    "isActive" BOOLEAN DEFAULT TRUE,
    "order" INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create updated_at trigger for billboards (reuse existing function)
CREATE TRIGGER update_billboards_updated_at 
    BEFORE UPDATE ON billboards 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 3. Create indexes for billboards
CREATE INDEX IF NOT EXISTS idx_billboards_order ON billboards("order");
CREATE INDEX IF NOT EXISTS idx_billboards_active ON billboards("isActive");

-- 4. Enable Row Level Security
ALTER TABLE billboards ENABLE ROW LEVEL SECURITY;

-- 5. Create policy to allow all operations on billboards
CREATE POLICY "Allow all operations on billboards" ON billboards
    FOR ALL 
    USING (true)
    WITH CHECK (true);

-- 6. Insert sample billboard data
INSERT INTO billboards (
    title, subtitle, description, "buttonText", "buttonUrl", "backgroundImage", "isActive", "order"
) VALUES 
('Exclusive Welcome Bonus', 'Get up to €500 + 200 Free Spins', 'Join now and claim your exclusive welcome package with amazing bonuses and free spins!', 'Claim Now', '#', '/Assets/place.svg', true, 1),
('VIP Casino Experience', 'Premium Gaming at Its Finest', 'Experience luxury gaming with our VIP program, exclusive games, and personal account managers.', 'Learn More', '#', '/Assets/place.svg', true, 2),
('Weekly Tournaments', 'Compete for €10,000 Prize Pool', 'Join our weekly casino tournaments and compete against players worldwide for massive prizes!', 'Join Tournament', '#', '/Assets/place.svg', true, 3)
ON CONFLICT (id) DO NOTHING;

-- ====================================================
-- STORAGE POLICIES FOR "boards" BUCKET
-- ====================================================
-- Make sure your "boards" bucket is created and set to PUBLIC

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Allow public uploads to boards" ON storage.objects;
DROP POLICY IF EXISTS "Allow public access to boards" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete from boards" ON storage.objects;

-- Create policy to allow anyone to upload images to boards bucket
CREATE POLICY "Allow public uploads to boards" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'boards');

-- Create policy to allow anyone to view images from boards bucket
CREATE POLICY "Allow public access to boards" ON storage.objects
FOR SELECT USING (bucket_id = 'boards');

-- Create policy to allow public deletion from boards bucket (optional)
CREATE POLICY "Allow public delete from boards" ON storage.objects
FOR DELETE USING (bucket_id = 'boards');

-- ====================================================
-- VERIFICATION QUERIES
-- ====================================================
-- Run these to verify everything is working:

-- Check if billboards table was created
SELECT * FROM billboards;

-- Check if storage policies are active
SELECT * FROM storage.objects WHERE bucket_id = 'boards'; 